##default config
spring:
  profiles:
    active: dev
  datasource:
    username: coupon
    password: coupon
    url: jdbc:postgresql://localhost:5432/coupon
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: validate
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    redis:
      repositories:
        enabled: false

  redis:
    database: 0
    host: localhost
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 5000
      min-idle: 0
    timeout: 1000

coupons:
  timeout:
    coupon-grant: 86400
    sell-coupon-grant: 86400
    user-coupon-share: 86400

endpoints:
  health:
    sensitive: false
server:
  port: 8080
management:
  health:
    db:
      enabled: true
    redis:
      enabled: true
    diskspace:
      enabled: true
  security:
    enabled: false

---
spring:
  profiles: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.chainz.coupon: DEBUG
#    org.hibernate: INFO
#    org.hibernate.type: trace

coupons:
  timeout:
    coupon-grant: 600
    sell-coupon-grant: 600
    user-coupon-share: 600

---
spring:
  profiles: ci
logging:
  level:
    com.chainz.coupon: INFO

coupons:
  timeout:
    coupon-grant: 600
    sell-coupon-grant: 600
    user-coupon-share: 600

---
spring:
  profiles: prod
logging:
  level:
    com.chainz.coupon: WARN
