##default config
spring:
  profiles:
    active: dev
  datasource:
    username: coupon
    password: coupon
    url: jdbc:postgresql://localhost:5432/coupon
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

endpoints:
  health:
    sensitive: false
server:
  port: 8080

---
spring:
  profiles: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.chainz.coupon: DEBUG

---
spring:
  profiles: ci
logging:
  level:
    com.chainz.coupon: INFO

---
spring:
  profiles: prod
logging:
  level:
    com.chainz.coupon: WARN
